name: Swift

on:
  push:
    branches:
    - develop
    - feature/*
    - bugfix/*
    - component/*
    
  pull_request:
    branches:
    - develop
    - feature/*
    - bugfix/*
    - component/*

jobs:
  build:
  
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Xcodegen
      run: |
        for d in `find . -name "*project.yml"`; 
        do (xcodegen generate --spec "$d"); 
        done
    - name: Dependencies
      run: |
        exec pod install
    - name: Xcode build
      run: |
        xcodebuild -workspace Project-Famili.xcworkspace -scheme LUMain -sdk iphonesimulator -destination "name=iPhone 8,OS=14.0" -quiet
    - name: Xcode tests
      run: |
        xcodebuild test -workspace Project-Famili.xcworkspace -scheme LUMain test-without-building -sdk iphonesimulator -destination "name=iPhone 8,OS=14.0" -quiet
